[project]
name = "class-06-mangodb"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "load-dotenv>=0.1.0",
    "pymongo[srv]>=4.12.0",
    "python-dotenv>=1.1.0",
]
